# NetCDF Diag Writing Layer
# Build configuration for nc_diag
# --------------------------------------------------------------------
# You should modify this file to set up the proper build configuration
# for nc_diag!
# --------------------------------------------------------------------
# Usage:
#     All you have to do is modify this file, and then build by using
#     "make"! You may add to this file, but NOT remove. Variables
#     that exist now should NOT be removed!
#     
#     Again, you may add your own variables to supplement the
#     build - but remember that we will be using our own NCLAYER_*
#     varables to build, so make sure your variables make it into our
#     NCLAYER_* variables!
#

# NCLAYER_FORT90C - Fortran 90 compiler
#   Specify the Fortran 90 compiler to use to compile nc_diag.
NCLAYER_FORT90C=ifort

# NCLAYER_F90FLAGS - Fortran 90 compiler flags
#   Specify the Fortran 90 compiler flags to use to compile
#   nc_diag. Any flags can be specified here, including
#   optimization flags that you may use in your programs.
NCLAYER_F90FLAGS+=

# NCLAYER_NETCDF_FLAGS - nc_diag NetCDF flags
#   Specify the required flags to compile nc_diag with NetCDF, a
#   required dependency. This should include the necessary include
#   files, as well as the correct linking directories and flags for
#   linking with NetCDF.
NCLAYER_NETCDF_FLAGS+=-I$(BASEDIR)/Linux/include/netcdf -L$(BASEDIR)/Linux/lib \
    -lnetcdff -lnetcdf -lhdf5 -lcurl -lz -lrt -lmpi -lhdf5_hl -lhdf5 \
    -lz -lsz -lgpfs -lmfhdf -ldf -ljpeg

# NCLAYER_CONFIG_FLAGS - nc_diag compile-time configuration flags
#   Specify nc_diag-specific options via compile-time flags.
#   
#   Available compile-time configuration flags:
#     -D_REAL8_            - define the default "real" number
#                            (other kinds defines available!)
#     -D_DEBUG_MEM_        - enable verbose memory debugging messages.
#                            WARNING - this is a LOT of messages!
#     -DANSI_TERM_COLORS   - enable terminal colors for warning and error
#                            messages.
#     -DERROR_TRACEBACK    - enable a traceback on error. This is useful
#                            for debugging any issues with code or
#                            NCLayer. This works by triggering a
#                            divide-by-zero runtime error, which in turn
#                            generates a traceback.
#     -DENABLE_ACTION_MSGS - enable messages that show the nc_diag API
#                            calls during execution.
NCLAYER_CONFIG_FLAGS+=-D_REAL8_ -DANSI_TERM_COLORS -DERROR_TRACEBACK -DENABLE_ACTION_MSGS

# NCLAYER_DEBUG - option to enable debugging flags when building
# nc_diag_res. This may override options set in NCLAYER_F90FLAGS.
NCLAYER_DEBUG=1

# NCLAYER_MAKE_ENABLE_FANCY_ANSI - fun little tongue twister that enables
# (or disables) fancy, colorful printing for nc_diag_res building.
# 
# If you want to add it to other targets:
#    -> Make sure you are specifying the source file to be compiled first!
#    -> If you are compiling a single module (or file):
#           Add a $(NCLAYER_MAKE_FANCY_BEGIN) to the start, and a
#           $(NCLAYER_MAKE_FANCY_END) to the end of the compile block.
#    -> If you are compiling a big file (a library, or an executable)
#       that compiles with all of the .o files:
#           Add a $(NCLAYER_MAKE_FANCY_BIG_BEGIN) to the start, and a
#           $(NCLAYER_MAKE_FANCY_BIG_END) to the end of the compile block.
#       Note that if you are just linking to a library, you can use
#       the regular one instead.
# 
# If you really don't like this option, and want to remove it from the
# entire Makefile system, do the following:
#    -> remove all $(NCLAYER_MAKE_FANCY_BEGIN), $(NCLAYER_MAKE_FANCY_END),
#       $(NCLAYER_MAKE_FANCY_BIG_BEGIN), and
#       $(NCLAYER_MAKE_FANCY_BIG_END) lines from ALL MAKEFILES
#    -> replace all $(NCLAYER_MAKE_QUIET) with nothing, e.g. replace
#           $(NCLAYER_MAKE_QUIET)somecmd
#               with
#           somecmd
#       ...from ALL MAKEFILES
#    -> remove the if block from this file (Makefile.config):
#           ifeq ($(NCLAYER_MAKE_ENABLE_FANCY_ANSI), 1)
#               ...
#           endif
#    -> remove this variable block from this file (Makefile.config)
NCLAYER_MAKE_ENABLE_FANCY_ANSI=0

#######################################################################
# Don't change anything below!
#######################################################################
# Fancy ANSI Makefile... oooh, fancy
ifeq ($(NCLAYER_MAKE_ENABLE_FANCY_ANSI), 1)
    NCLAYER_MAKE_FANCY_BEGIN = @printf "\033[1m\033[34m ** Building $< => $@...\033[0m\n"
    NCLAYER_MAKE_QUIET = @
    NCLAYER_MAKE_FANCY_END = @printf "\033[F\r\033[32m ** Building $< => $@... done!\033[0m\n"
    
    NCLAYER_MAKE_FANCY_BIG_BEGIN = @printf "\033[1m\033[34m ** Building $@...\033[0m\n"
    NCLAYER_MAKE_FANCY_BIG_END = @printf "\033[F\r\033[32m ** Building $@... done!\033[0m\n"
else
    NCLAYER_MAKE_FANCY_BEGIN = 
    NCLAYER_MAKE_QUIET = 
    NCLAYER_MAKE_FANCY_END = 
    NCLAYER_MAKE_FANCY_BIG_BEGIN = 
    NCLAYER_MAKE_FANCY_BIG_END = 
endif

# Coverage build flags
ifndef COVERAGE
    COVERAGE=0
endif

ifeq ($(COVERAGE), 1)
    NCLAYER_F90FLAGS+=-prof-gen=srcpos
endif

# Add debug flags
ifeq ($(NCLAYER_DEBUG), 1)
    NCLAYER_F90FLAGS+=-O0 -fpp -g -pg -check all \
        -ftrapuv -debug all -fpe0 -warn all -traceback -debug extended
endif
