# NetCDF Diag Read Library
# Build configuration for nc_diag_res
# --------------------------------------------------------------------
# You should modify this file to set up the proper build configuration
# for nc_diag_res!
# --------------------------------------------------------------------
# Usage:
#     All you have to do is modify this file, and then build by using
#     "make"! You may add to this file, but NOT remove. Variables
#     that exist now should NOT be removed!
#     
#     Again, you may add your own variables to supplement the
#     build - but remember that we will be using our own NCDRES_*
#     varables to build, so make sure your variables make it into our
#     NCDRES_* variables!
#

# NCDRES_FORT90C - Fortran 90 compiler
#   Specify the Fortran 90 compiler to use to compile nc_diag_res.
NCDRES_FORT90C=ifort

# NCDRES_F90FLAGS - Fortran 90 compiler flags
#   Specify the Fortran 90 compiler flags to use to compile
#   nc_diag_res. Any flags can be specified here, including
#   optimization flags that you may use in your programs.
NCDRES_F90FLAGS+=

# NCDRES_CONFIG_FLAGS - nc_diag_res compile-time configuration flags
#   Specify nc_diag_res-specific options via compile-time flags.
#   
#   Available compile-time configuration flags:
#     -D_REAL8_          - define the default "real" number
#                          (other kinds defines available!)
#     -D_DEBUG_MEM_      - enable verbose memory debugging messages.
#                          WARNING - this is a LOT of messages!
#     -DANSI_TERM_COLORS - enable terminal colors for warning and error
#                          messages.
#     -DERROR_TRACEBACK  - enable a traceback on error. This is useful
#                          for debugging any issues with code or
#                          nc_diag_res. This works by triggering a
#                          divide-by-zero runtime error, which in turn
#                          generates a traceback.
NCDRES_CONFIG_FLAGS+=-D_REAL8_ -DANSI_TERM_COLORS -DERROR_TRACEBACK

# Debug setup
ifndef NCDRES_DEBUG
    NCDRES_DEBUG=0
endif

# Debug flags
ifeq ($(NCDRES_DEBUG), 1)
    NCDRES_F90FLAGS+=-O0 -fpp -g -pg -check all \
        -ftrapuv -debug all -fpe0 -warn all -traceback -debug extended
endif
